export const common = [];

export const themesList = [
  { theme: 'blue', name: '民生蓝' },
  { theme: 'red', name: '金融红' },
  { theme: 'bumblebee', name: '黄蜂' },
  { theme: 'retro', name: '复古' },
  { theme: 'garden', name: '花园' },
  { theme: 'cyberpunk', name: '赛博朋克' },
  { theme: 'lofi', name: '简约' },
  { theme: 'wireframe', name: '线框' },
  { theme: 'autumn', name: '秋季' },
  { theme: 'lemonade', name: '青柠' },
  { theme: 'cupcake', name: '纸杯蛋糕' },
  { theme: 'valentine', name: '七夕' },
  { theme: 'pastel', name: '淡雅' },
  { theme: 'aqua', name: '湖绿' },
  { theme: 'cmbcdark', name: '深色' },
  { theme: 'halloween', name: '狂欢' },
  { theme: 'forest', name: '森林' },
  { theme: 'luxury', name: '豪华' },
  { theme: 'dracula', name: '德古拉' },
  { theme: 'synthwave', name: '合成波' },
  { theme: 'night', name: '暗夜' },
  { theme: 'coffee', name: '咖啡' },
  { theme: 'black', name: '纯黑' },
];
